export const formList = {
    income: {
        saved: false,
        isSubmit: true,
        earnedIncome: '',
        profitIncome:'',
        interestIncome:'',
        dividedIncome: '',
        rentalIncome:'',
        capitalIncome:'',
        royaltyIncome: '',
        year:'',
        otherIncome:'',
        country: '',
        state: '',
        zipcode: '',
        nameIncome: '',
        isRecentIncome: true,
        incomeComments: '',
        documents: []
    },
    optCurrentyear:['Yes','No'],
    localeByCountry: {
        'IN': 'en-IN',
        'US': 'ens-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    assets: {
            saved: false,
            isSubmit: true,
            cashEqual: '',
            profitIncome:'',
            inventory:'',
            investments: '',
            plantAssets:'',
            vehiclesAssets:'',
            furnitureAssets: '',
            assetsyear:'',
            otherAssets:'',
            country: '',
            state: '',
            zipcode: '',
            nameAssetss: '',
            isRecentAssets: true,
            assetsComments: '',
            documents: []
    },
    optAssetsyear:['Yes', 'No'],
    liability: {
        saved: false,
        isSubmit: true,
        accountPayable:'',
        liability:'',
        shortLoan:'',
        taxesPayable:'',
        accountExpenses:'',
        unearnedExpense:'',
        notesPayable:'',
        mortgagePayable:'',
        bondsPayable:'',
        taxLiability:'',
        liabilityYear:'',
        otherliability:'',
        optLiabilyyear:'',
        personName: '',
        country: '',
        state: '',
        zipcode: '',
        issuedOn: '',
        expirationOns: '',
        eligibleRenewal: '',
        isRecentIdentity: true,
        identityComments: '',
        documents: [],
    },
    
    monthlyexpense: {
        saved: false,
        isSubmit: true,
        water:'',
        trash:'',
        gas:'',
        transport:'',
        automa:'',
        personName: '',
        country: '',
        state: '',
        zipcode: '',
        issuedOn: '',
        expirationOns: '',
        eligibleRenewal: '',
        isRecentIdentity: true,
        identityComments: '',
        documents: [],
    }
    
};