export const formList = {
    income: {
        saved: false,
        isSubmit: true,
        earnedIncome: '',
        profitIncome:'',
        interestIncome:'',
        dividedIncome: '',
        rentalIncome:'',
        capitalIncome:'',
        royaltyIncome: '',
        year:'',
        otherIncome:'',
        country: '',
        state: '',
        zipcode: '',
        nameIncome: '',
        isRecentIncome: true,
        incomeComments: '',
        documents: []
    },
    optCurrentyear:['Yes','No'],
    optFName:['Yes','No'],
    localeByCountry: {
        'IN': 'en-IN',
        'US': 'ens-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    assets: {
            saved: false,
            isSubmit: true,
            cashEqual: '',
            profitIncome:'',
            inventory:'',
            investments: '',
            plantAssets:'',
            vehiclesAssets:'',
            furnitureAssets: '',
            assetsyear:'',
            otherAssets:'',
            total:'',
            country: '',
            state: '',
            zipcode: '',
            nameAssets: '',
            isRecentAssets: true,
            assetsComments: '',
            documents: []
    },
    optAssetsyear:['Yes', 'No'],
    liability: {
        saved: false,
        isSubmit: true,
        accountPayable:'',
        liability:'',
        shortLoan:'',
        taxesPayable:'',
        accountExpenses:'',
        unearnedExpense:'',
        notesPayable:'',
        mortgagePayable:'',
        bondsPayable:'',
        taxLiability:'',
        liabilityYear:'',
        otherliability:'',
        country: '',
        state: '',
        zipcode: '',
        isRecentIdentity: true,
        identityComments: '',
        documents: [],
    },
    
    monthlyexpense: {
        saved: false,
        isSubmit: true,
        water:'',
        trash:'',
        gas:'',
        transport:'',
        automa:'',
        carReg:'',
        carIns:'',
        homeMa:'',
        homeIns:'',
        healthCare:'',
        clothing:'',
        gifts:'',
        charitable:'',
        software:'',
        entertainment:'',
        vacation:'',
        transportFin:'',
        compFin:'',
        gymFin:'',
        education:'',
        gaming:'',
        celebration:'',
        beauty:'',
        propTax:'',
        movie:'',
        phone:'',
        lifeIns:'',
        membership:'',
        cCard:'',
        houseMain:'',
        banking:'',
        houseHold:'',
        petCare:'',
        childCare:'',
        kidsActivity:'',
        schoolFees:'',
        weddings:'',
        taxes:'',
        lawnCare:'',
        otherFin:'',
        monthFin:'',
        yearFin:'',
        personName: '',
        total:'',
        eligibleRenewal: '',
        isRecentIdentity: true,
        identityComments: '',
        documents: [],
    }
    
};