export const formList = {
    general: {
        saved: false,
        isSubmit: true,
        firstName: '',
        lastName: '',
        houseSize: '',
        address1:'',
        address2:'',
        landmark:'',
        houseYear:'',
        country: '',
        state: '',
        zipcode: '',
        isRecentGeneral: true,
        generalComments: '',
        documents: []
    },
    genderType:['Male', 'Female'],
    houseType:['condo','townhouse'],
    solar:['Yes','No'],
    localeByCountry: {
        'IN': 'en-IN',
        'US': 'en-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    hospitalName:['Medi Cure', 'Medi Care', 'Miniute Clinic'],
    bloodGroup:['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    houseAddress:['#4567', '#4567gunia' , '#4567 Marshall'],
    apgarScore:['AAA', 'BBB'],
    otherScore:['A+', 'A', 'B+'],
    house: {
        saved: false,
        isSubmit: true,
        puchasYear:'',
        warrantyYear:'',
        warrantyExpire: '',
        totalCost:'',
        address1:'',
        house:true,
        extYear:'',
        partywarranty: '',
        isRecenthouse: true,
        houseComments: '',
        documents: [],
    },
    holdItems:['Mixer','Washing Mechine'],
    purchasType:['Condo','Townhall'],
    venderName:['Justin','Hema'],
    houseMake:['Aaa','BBB'],
    ExtWarrenty:['Yes', 'No'],
    partySupport:['Yes', 'No'],
    optDoseValues:['Yes', 'No'],
    houseitems: {
        saved: false,
        isSubmit: true,
        puchasYear:'',
        warrantyYear:'',
        warrantyExpire: '',
        totalCost:'',
        houseitems:true,
        extYear:'',
        partywarranty: '',
        isRecentImmune: true,
        houseitemsComments: '',
        documents: [],
    },
    houseitemsType: ['LLC'],
    vehicles: {
        saved: false,
        isSubmit: true,
        isRecentvehicles: true,
        vehiclescomments: '',
        documents: [],
    },
    vehiclesType: ['LLC'] 
};