export const formList = {
    regular: {
        saved: false,
        isSubmit: true,
        firstName: '',
        lastName: '',
        regularType: '',
        age:'',
        country: '',
        state: '',
        zipcode: '',
        from: '',
        bodyMI:'',
        bcbs:'',
        medicalShop:'',
        isRecentRegular: true,
        regularComments: '',
        documents: []
    },
    regularType: ['Male', 'Female', 'Other'],
    localeByCountry: {
        'IN': 'en-IN',
        'US': 'en-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    hospitalName:['Medi Cure', 'Medi Care', 'Miniute Clinic'],
    bloodGroup:['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    doctorName:['Rajashekar', 'Vijaya', 'Latha'],
    immuneName:['Covid', 'Flu' , 'Booster'],
    apgarScore:['AAA', 'BBB'],
    otherScore:['A+', 'A', 'B+'],
    immune: {
        saved: false,
        isSubmit: true,
        immuneName:'',
        hospitalName: '',
        from:'',
        country: '',
        state: '',
        zipcode: '',
        lastDose: '',
        doseName:'',
        immuneDose:true,
        age:'',
        isRecentImmune: true,
        immuneComments: '',
        documents: [],
    },
    immuneType: ['Flu','Covid'],
    optDose:['Yes', 'No'],
    secondDose:['Yes', 'No'],
    optDoseValues:['Yes', 'No'],
    allergi: {
        saved: false,
        isSubmit: true,
        country: '',
        state: '',
        zipcode: '',
        from: '',
        isRecentBusiness: true,
        allergiComments: '',
        documents: [],
    },
    
    healthinfo: {
        saved: false,
        isSubmit: true,
        firstName: '',
        lastName: '',
        height:'',
        weight:'',
        age:'',
        country: '',
        state: '',
        zipcode: '',
        from: '',
        bloodPressure:'',
        bodymIndex:'',
        bcbs:'',
        medicalShop:'',
        isRecentRegular: true,
        healthinfoComments: '',
        documents: []
    },
    healthinfoType: ['TB', 'Flue', 'FEver'],
    surgery: {
        saved: false,
        isSubmit: true,
        hospitalName: '',
        surgeryDate:'',
        dischargeDate:'',
        followdate:'',
        country: '',
        state: '',
        zipcode: '',
        surgeryUnit:'',
        insuranceHelp:true,
        insureCovered:'',
        salary: '',
        isRecentSurgery: true,
        surgeryComments: '',
        documents: [],
    },
    surgeryType: ['LLC', 'Ortho'],
    status:['Yes', 'No'],
    medication: {
        saved: false,
        isSubmit: true,
        medicineName: '',
        medicineDose: '',
        providerName:'',
        pharmacyDetail:'',
        from: '',
        to: '',
        isRecentMedication: true,
        medicationComments: '',
        documents: [],
    },
    medicationType: ['Flu' , 'Cold'],
    refill:['Yes' , 'No'],
};