export const formList = {
    hinsurance: {
        saved: false,
        isSubmit: true,
        idNumber: '',
        specialVisit: '',
        primaryCare:'',
        insuranceType: '',
        urgentValue:'',
        emergencyValue:'',
        nofMembers:'',
        country: '',
        state: '',
        zipcode: '',
        from: '',
        to: '',
        isRecentRegular: true,
        insuranceComments: '',
        documents: []
    },
    insuranceType:['ortho', 'eye'],
    insureProvidName:['United', 'Health Insurance'],
    insureGroupdName:['A Group', 'B Group'],
    insureStatus: ['Active', 'Inactive'],
    localeByCountry: {
        'IN': 'en-IN',
        'US': 'en-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    hospitalName:['Medi Cure', 'Medi Care', 'Miniute Clinic'],
    bloodGroup:['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    doctorName:['Rajashekar', 'Vijaya', 'Latha'],
    immuneName:['Covid', 'Flu' , 'Booster'],
    apgarScore:['AAA', 'BBB'],
    otherScore:['A+', 'A', 'B+'],
    result: {
        saved: false,
        isSubmit: true,
        resultName: '',
        resultDate:'',
        collectedDate:'',
        resultUnit: '',
        orderDate:'',
        insuranceHelp:true,
        labName:'',
        resultValue: '',
        isRecentSurgery: true,
        resultComments: '',
        documents: [],
    },
    resultType: ['LLC', 'Ortho'],
    
    medication: {
        saved: false,
        isSubmit: true,
        businessName: '',
        businessTitle: '',
        businessType: '',
        country: '',
        state: '',
        zipcode: '',
        from: '',
        to: '',
        salary: '',
        isRecentBusiness: true,
        comments: '',
        documents: [],
    },
    businessType: ['LLC'],
    monthlypay: {
        saved: false,
        isSubmit: true,
        firstName: '',
        lastName: '',
        houseSize: '',
        address1:'',
        address2:'',
        landmark:'',
        houseYear:'',
        country: '',
        state: '',
        zipcode: '',
        isRecentGeneral: true,
        monthlypayComments: '',
        documents: []
    },
    genderType:['Male', 'Female'],
    houseType:['condo','townhouse'],
    solar:['Yes','No'],
    insuranceName:['Allied', 'United' , 'Health Care'],
    insuranceCompany:['Allied', 'United' , 'Health Care'],
    propertypay: {
        saved: false,
        isSubmit: true,
        policyNumber:'',
        policyPeriod:'',
        policyAddress:'',
        totalPremium:'',
        dwelling: '',
        loYear:'',
        dedectibles:'',
        otherStructure:'',
        personalLiability:'',
        personalProperties:'',
        windhail:'',
        midPay:'',
        otherPeris:'',
        additionalCoverage:'',
        isRecentImmune: true,
        houseitemsComments: '',
        documents: [],
    },
    houseitemsType: ['LLC'],
    holdItems:['Mixer','Washing Mechine'],
    purchasType:['Condo','Townhall'],
    venderName:['Justin','Hema'],
    houseMake:['Aaa','BBB'],
    ExtWarrenty:['Yes', 'No'],
    partySupport:['Yes', 'No'],
    optDoseValues:['Yes', 'No'],
    vehiclespay: {
        saved: false,
        isSubmit: true,
        isRecentvehicles: true,
        VehiclesComments: '',
        documents: [],
    },
    vehiclesType: ['LLC'],
    vehiclesCompany:['Honda','Zen'],
    
};