export const formList = {
    personal: {
        saved: false,
        isSubmit: true,
        personName: '',
        country: '',
        state: '',
        zipcode: '',
        issuedOn: '',
        expirationOns: '',
        eligibleRenewal: '',
        isRecentPersonal: true,
        personalComments: '',
        documents: []
    },
    orgName:['School', 'College'],
    certificateName:['Sports','Degree'],
    certifStatus:['Active', 'InActive'],
    optRenewal:['Yes','No'],
    eligibleType:['Eligible', 'Ineligible'],
    localeByCountry: {
        'IN': 'en-IN',
        'US': 'ens-US'
    },
    currencyByCountry: {
        'IN': 'INR',
        'US': 'USD'
    },
    hospitalName:['Medi Cure', 'Medi Care', 'Miniute Clinic'],
    bloodGroup:['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'],
    houseAddress:['#4567', '#4567gunia' , '#4567 Marshall'],
    apgarScore:['AAA', 'BBB'],
    otherScore:['A+', 'A', 'B+'],
    religious: {
        saved: false,
        isSubmit: true,
        personName: '',
        country: '',
        state: '',
        zipcode: '',
        issuedOn: '',
        expirationOns: '',
        eligibleRenewal: '',
        isRecentPersonal: true,
        personalComments: '',
        documents: []
    },
    
    holdItems:['Mixer','Washing Mechine'],
    purchasType:['Condo','Townhall'],
    venderName:['Justin','Hema'],
    houseMake:['Aaa','BBB'],
    ExtWarrenty:['Yes', 'No'],
    partySupport:['Yes', 'No'],
    optDoseValues:['Yes', 'No'],
    identity: {
        saved: false,
        isSubmit: true,
        personName: '',
        country: '',
        state: '',
        zipcode: '',
        issuedOn: '',
        expirationOns: '',
        eligibleRenewal: '',
        isRecentIdentity: true,
        identityComments: '',
        documents: [],
    },
    houseitemsType: ['LLC'],
    vehicles: {
        saved: false,
        isSubmit: true,
        personName: '',
        country: '',
        state: '',
        zipcode: '',
        issuedOn: '',
        expirationOns: '',
        eligibleRenewal: '',
        isRecentEducation: true,
        educationComments: '',
        documents: [],
    },
    vehiclesType: ['LLC'] 
};